export { default as orderedPair } from './orderedPair.ts';
export { default as interpolate } from './interpolate.ts';
export { default as is } from './is/mod.ts';
export * from './vdom/mod.ts';
export { default as diff } from './diff/mod.ts';
export * from './diff/mod.ts';
export { default as createWhich } from './createWhich.ts';
export * from './createWhich.ts';
export { default as createRoute } from './createRoute.ts';
export * from './types.ts';