/**
 * @author Hans Oksendahl
 */
import { createHTML, HTMLTags } from '../mod.ts';
import imbueTextValueParams from './imbueTextValueParams.ts';
import { ComponentParams } from './types.ts';

function createAbstractHTML<T extends HTMLTags>(
  tag: T
) {
  return (...params: ComponentParams) => {
    // Take a pristine abstract representation of a namespaced HTML tag.
    const node = createHTML(tag)
    
    // Imbue it with magical powers.
    imbueTextValueParams(params, node);

    return node;
  };
}

// Create factory functions for the following
export default {
  a: createAbstractHTML('a'),
  abbr: createAbstractHTML('abbr'),
  acronym: createAbstractHTML('acronym'),
  address: createAbstractHTML('address'),
  applet: createAbstractHTML('applet'),
  area: createAbstractHTML('area'),
  article: createAbstractHTML('article'),
  aside: createAbstractHTML('aside'),
  audio: createAbstractHTML('audio'),
  b: createAbstractHTML('b'),
  base: createAbstractHTML('base'),
  basefont: createAbstractHTML('basefont'),
  bdi: createAbstractHTML('bdi'),
  bdo: createAbstractHTML('bdo'),
  big: createAbstractHTML('big'),
  blockquote: createAbstractHTML('blockquote'),
  body: createAbstractHTML('body'),
  br: createAbstractHTML('br'),
  button: createAbstractHTML('button'),
  canvas: createAbstractHTML('canvas'),
  caption: createAbstractHTML('caption'),
  center: createAbstractHTML('center'),
  cite: createAbstractHTML('cite'),
  code: createAbstractHTML('code'),
  col: createAbstractHTML('col'),
  colgroup: createAbstractHTML('colgroup'),
  data: createAbstractHTML('data'),
  datalist: createAbstractHTML('datalist'),
  dd: createAbstractHTML('dd'),
  del: createAbstractHTML('del'),
  details: createAbstractHTML('details'),
  dfn: createAbstractHTML('dfn'),
  dialog: createAbstractHTML('dialog'),
  dir: createAbstractHTML('dir'),
  div: createAbstractHTML('div'),
  dl: createAbstractHTML('dl'),
  dt: createAbstractHTML('dt'),
  em: createAbstractHTML('em'),
  embed: createAbstractHTML('embed'),
  fieldset: createAbstractHTML('fieldset'),
  figcaption: createAbstractHTML('figcaption'),
  figure: createAbstractHTML('figure'),
  font: createAbstractHTML('font'),
  footer: createAbstractHTML('footer'),
  form: createAbstractHTML('form'),
  frame: createAbstractHTML('frame'),
  frameset: createAbstractHTML('frameset'),
  h1: createAbstractHTML('h1'),
  h2: createAbstractHTML('h2'),
  h3: createAbstractHTML('h3'),
  h4: createAbstractHTML('h4'),
  h5: createAbstractHTML('h5'),
  h6: createAbstractHTML('h6'),
  head: createAbstractHTML('head'),
  header: createAbstractHTML('header'),
  hr: createAbstractHTML('hr'),
  html: createAbstractHTML('html'),
  i: createAbstractHTML('i'),
  iframe: createAbstractHTML('iframe'),
  img: createAbstractHTML('img'),
  input: createAbstractHTML('input'),
  ins: createAbstractHTML('ins'),
  kbd: createAbstractHTML('kbd'),
  label: createAbstractHTML('label'),
  legend: createAbstractHTML('legend'),
  li: createAbstractHTML('li'),
  link: createAbstractHTML('link'),
  main: createAbstractHTML('main'),
  map: createAbstractHTML('map'),
  mark: createAbstractHTML('mark'),
  meta: createAbstractHTML('meta'),
  meter: createAbstractHTML('meter'),
  nav: createAbstractHTML('nav'),
  noframes: createAbstractHTML('noframes'),
  noscript: createAbstractHTML('noscript'),
  object: createAbstractHTML('object'),
  ol: createAbstractHTML('ol'),
  optgroup: createAbstractHTML('optgroup'),
  option: createAbstractHTML('option'),
  output: createAbstractHTML('output'),
  p: createAbstractHTML('p'),
  param: createAbstractHTML('param'),
  picture: createAbstractHTML('picture'),
  pre: createAbstractHTML('pre'),
  progress: createAbstractHTML('progress'),
  q: createAbstractHTML('q'),
  rp: createAbstractHTML('rp'),
  rt: createAbstractHTML('rt'),
  ruby: createAbstractHTML('ruby'),
  s: createAbstractHTML('s'),
  samp: createAbstractHTML('samp'),
  script: createAbstractHTML('script'),
  section: createAbstractHTML('section'),
  select: createAbstractHTML('select'),
  small: createAbstractHTML('small'),
  source: createAbstractHTML('source'),
  span: createAbstractHTML('span'),
  strike: createAbstractHTML('strike'),
  strong: createAbstractHTML('strong'),
  style: createAbstractHTML('style'),
  sub: createAbstractHTML('sub'),
  summary: createAbstractHTML('summary'),
  sup: createAbstractHTML('sup'),
  svg: createAbstractHTML('svg'),
  table: createAbstractHTML('table'),
  tbody: createAbstractHTML('tbody'),
  td: createAbstractHTML('td'),
  template: createAbstractHTML('template'),
  textarea: createAbstractHTML('textarea'),
  tfoot: createAbstractHTML('tfoot'),
  th: createAbstractHTML('th'),
  thead: createAbstractHTML('thead'),
  time: createAbstractHTML('time'),
  title: createAbstractHTML('title'),
  tr: createAbstractHTML('tr'),
  track: createAbstractHTML('track'),
  tt: createAbstractHTML('tt'),
  u: createAbstractHTML('u'),
  ul: createAbstractHTML('ul'),
  var: createAbstractHTML('var'),
  video: createAbstractHTML('video'),
  wbr: createAbstractHTML('wbr')
};